title: "Georges Mbissane SARR"
email: georgesmbissanes@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio website!
baseurl: "/" 
url: "https://geosarr.github.io" 
twitter_username: 
github_username: geosarr

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg
